### ISSUE TITLE
Support for serving binaries from GitHub Releases

### ISSUE THREAD

**Issue by awonak** [dbuezas/arduino-web-uploader#10]
In my repository I use GitHub Actions to compile a few firmwares with a set of flags to build binaries for three common Arduino Nano clones.

This action is triggered when a new tag is pushed with the semantic version pattern, like "vX.Y.Z". After the binaries are created, a new GitHub release is added and all of the firmware binaries are attached to the release.

I would like to be able to use the GitHub latest release assets as the source of my .hex files with the arduino-web-uploader library. 

Here is the GitHub action file I use to build the binaries, create the release, and attach the binaries to the release assets.

https://github.com/awonak/HagiwoModulove/blob/main/.github/workflows/build_release.yml

Related issue: https://github.com/modulove/A-RYTH-MATIK/issues/10

**Comment by dbuezas** [comment]
See "use as node module" in the readme. You can pass the url of the hex file in JavaScript
